Add option to remove NVG when adding flashlights
zen-mod/ZEN pull request #517
Opened 2021-01-18 02:57 UTC by neilzar

**When merged this pull request will:**
- Closes #471 
- Extend the `Add flashlight module` with an option to remove NVGs when enabling flashlights.

2021-01-19 14:51 UTC, mharis001 commented on addons/modules/functions/fnc_moduleToggleFlashlights.sqf
> +            _nvg = assignedItems _x select 5;
`assignedItems` does not guarantee that NVGs are always at index 5.

2021-01-22 14:08 UTC, CreepPork requested changes

2021-01-22 14:08 UTC, CreepPork commented on addons/modules/stringtable.xml
> +            <English>Remove NVG</English>
```suggestion
            <English>Remove NVGs</English>
```

2021-01-22 22:08 UTC, mharis001 commented on addons/modules/functions/fnc_moduleToggleFlashlights.sqf
> +            _nvg = hmd _x;
Missing `private` and could also be moved into `if` after `_removeNVG` is checked.

2021-01-22 22:08 UTC, mharis001 commented on addons/modules/stringtable.xml
> +            <English>Remove any Night Vision Goggles currently equiped.</English>
I think: "Remove any currently equipped Night Vision Goggles." reads a bit better. Also, equipped is misspelled.

2021-01-24 04:12 UTC, mharis001 commented on addons/modules/functions/fnc_moduleToggleFlashlights.sqf
> +            };
This won't work now. I meant something like this:
```sqf
if (_removeNVG) then {
    private _nvg = hmd _x;

    if (_nvg != "") then {
        // ...
```

2021-02-03 05:20 UTC, mharis001 commented on addons/common/XEH_postInit.sqf
> +}] call CBA_fnc_addEventHandler;
`unlinkItem` is AG/EG so we don't need to use target events.

2021-02-04 04:46 UTC, mharis001 commented on addons/modules/functions/fnc_moduleToggleFlashlights.sqf
> +                    _unit unlinkItem _x;
Should be `_nvg` instead of `_x`.

2021-02-04 15:35 UTC, mharis001 approved these changes

2021-02-07 20:33 UTC, CreepPork approved these changes

2021-02-07 20:36 UTC, merged