Common - Filter for ACRE radio IDs when serializing objects
zen-mod/ZEN pull request #640
Opened 2021-10-02 03:35 UTC by mjc4wilton

**When merged this pull request will:**
- Add CfgPatches check for ACRE via Common `postInit.sqf`
- If ACRE is installed, pass the loadout through to `acre_api_fnc_filterUnitLoadout` to remove replace ACRE radio IDs with base radios
- Fix #636

2021-11-01 01:51 UTC, mharis001 requested changes
If we go with this approach then I would want to add TFAR support (doesn't need to be in this PR). We could also try and hold out for the extended loadout framework proposed for CBA but not sure when (or if) that will be merged.

Overall, seems okay, but maybe we should have our own get/set loadout functions in `common` instead of duplicating code.

2021-11-01 01:51 UTC, mharis001 commented on addons/common/XEH_postInit.sqf
> +};
Doesn't need the `if` block.

2021-11-01 01:51 UTC, mharis001 commented on addons/context_actions/CfgContext.hpp
> +            statement = QUOTE(if !(GVAR(hasACRE)) then {GVAR(loadout) = getUnitLoadout _hoveredEntity;} else {GVAR(loadout) = [getUnitLoadout _hoveredEntity] call acre_api_fnc_filterUnitLoadout;});
This seems weird, also `GVAR(hasACRE)` is incorrect here.

2021-11-29 15:47 UTC, Kexanone commented
@mharis001
When do we prefer event handlers over functions?

Also I'm not really sure if the `safe` postfix is really necessary.

2021-11-29 15:52 UTC, Kexanone commented on addons/context_actions/CfgContext.hpp
> +            statement = QUOTE(GVAR(loadout) = [ARR_1(_hoveredEntity)] call EFUNC(common,getUnitLoadoutSafe););
```suggestion
            statement = QUOTE(GVAR(loadout) = _hoveredEntity call EFUNC(common,getUnitLoadoutSafe););
```

2021-11-29 15:57 UTC, Kexanone commented on addons/common/functions/fnc_getUnitLoadoutSafe.sqf
> +return _loadout;
```suggestion
_loadout // Return value
```
This is not `C++` 😅

2021-11-29 19:43 UTC, mjc4wilton commented
> Also I'm not really sure if the `safe` postfix is really necessary.

Did it so its not just getUnitLoadout wrapped in a macro. Not necessary but helps maintain syntax highlighting

2022-01-26 19:16 UTC, mharis001 reviewed
Looks good. Just some cleanup.

2022-01-26 19:16 UTC, mharis001 commented on addons/common/XEH_PREP.hpp
> +PREP(getUnitLoadoutSafe);
Change function name to `getUnitLoadout`.

2022-01-26 19:16 UTC, mharis001 commented on addons/common/functions/fnc_getUnitLoadoutSafe.sqf
> +if (isClass(configFile >> "CfgPatches" >> "acre_main")) then {
```suggestion
if (isClass (configFile >> "CfgPatches" >> "acre_main")) then {
```

2022-01-26 19:16 UTC, mharis001 commented on addons/common/functions/fnc_getUnitLoadoutSafe.sqf
> + * [player] call zen_common_fnc_getUnitLoadoutSafe
```suggestion
 * [_unit] call zen_common_fnc_getUnitLoadout
```

2022-01-26 19:16 UTC, mharis001 commented on addons/common/functions/fnc_getUnitLoadoutSafe.sqf
> +_loadout // Return value
```suggestion
_loadout
```

2022-01-26 19:16 UTC, mharis001 commented on addons/context_actions/CfgContext.hpp
> +            statement = QUOTE(GVAR(loadout) = _hoveredEntity call EFUNC(common,getUnitLoadoutSafe););
```suggestion
            statement = QUOTE(GVAR(loadout) = _hoveredEntity call EFUNC(common,getUnitLoadout));
```

2022-01-26 19:16 UTC, mharis001 commented on addons/common/functions/fnc_getUnitLoadoutSafe.sqf
> + * Returns the unit loadout array (sanitized)
```suggestion
 * Returns the given unit's loadout. Handles filtering items with unique radio IDs.
```

2022-01-26 19:58 UTC, mharis001 commented on addons/common/functions/fnc_exportMissionSQF.sqf
> +            private _loadout = [_object] call FUNC(getUnitLoadoutSafe);
Function name needs to be updated here and in other places.

2022-01-27 02:38 UTC, mharis001 approved these changes

2022-01-27 02:48 UTC, Kexanone approved these changes

2022-02-09 19:34 UTC, merged