Add mod icons to create unit trees
zen-mod/ZEN pull request #684
Opened 2022-10-01 04:55 UTC by mharis001

**When merged this pull request will:**
- title, Close #207

2022-11-15 20:36 UTC, neilzar approved these changes

2022-12-03 00:00 UTC, Kexanone requested changes
Looks fine, but changing the setting should trigger reloading the module tree.

2022-12-03 02:54 UTC, mharis001 commented
ZEN is sort of split on that right now. Some settings reload the display automatically (e.g. faction filter) while others apply once the display is manually reloaded (e.g. the similar group icons setting). I guess if we change it here, the behaviour should be made consistent across all features.

2022-12-03 03:11 UTC, Kexanone commented
> ZEN is sort of split on that right now. Some settings reload the display automatically (e.g. faction filter) while others apply once the display is manually reloaded (e.g. the similar group icons setting). I guess if we change it here, the behaviour should be made consistent across all features.

Agreed, we should have a dedicated PR for that. In fact I was about to make the same comment for the placement preview, but thought it was out of scope for that PR.

2022-12-03 03:12 UTC, Kexanone approved these changes

2022-12-03 03:40 UTC, merged